nvim: Change some telescope mappings to be more consistent, scripts: Update pv-check-device.

diff --git a/scripts/.local/bin/pv-check-device b/scripts/.local/bin/pv-check-device
--- a/scripts/.local/bin/pv-check-device
+++ b/scripts/.local/bin/pv-check-device
@@ -2,18 +2,87 @@
 
 set -eo pipefail
 
+usage() {
+	printf "Use like:\n\t %s    [device]    [imagefile]\n\t %s -d [device] -i [imagefile]\n" "$0" "$0" 1>&2
+	exit 1
+}
+
+check_device() {
+	local device=$1
+	local imagefile=$2
+	if [[ -z "$device" || -z "$imagefile" ]]; then
+		usage
+	elif [[ ! -f "$imagefile" ]]; then
+		echo "Image file '$imagefile' does not exist"
+		usage
+	fi
+
+	local device_info
+	device_info=$(udevadm info --query=property --path="/sys/block/${device##*/}")
+	local device_bus
+	device_bus=$(perl <<<"$device_info" -ne '/^ID_BUS=(.*)/ && print $1')
+	local device_size_suffixed
+	device_size_suffixed=$(lsblk -o SIZE "$device" | head -2 | tail -1)
+	local device_size
+	device_size=$(perl <<<"$device_size_suffixed" -ne '/\s*([\d\.]+)G/ && print $1')
+
+	set -x
+	if [[ "$device_bus" != "usb" ]]; then
+		echo "Device $device is not a usb device?"
+		exit 2
+	elif [[ "$(bc <<<"${device_size:-0} < 8")" -eq 1 ]]; then
+		echo "Device $device seems to be too small? $device_size_suffixed"
+		exit 1
+	elif [[ "$(bc <<<"${device_size} > 512")" -eq 1 ]]; then
+		read -rp "Device is size $device_size_suffixed, seems a bit large, are you sure? [y/N] " res
+		case "$res" in
+		[yY] | [yY][eE][sS]) ;;
+		*)
+			echo 'Exiting'
+			exit 1
+			;;
+		esac
+	elif mount | grep -qF "$device"; then
+		echo "Device $device is mounted"
+		exit 1
+	fi
+}
+
+flash_image() {
+	local device=$1
+	local imagefile=$2
+
+	if [[ -z "$device" || -z "$imagefile" ]]; then
+		echo "Error: device and imagefile arguments are required" 1>&2
+		return 1
+	fi
+
+	local ext=${imagefile##*.}
+	case "$ext" in
+	zip | 7zip)
+		sudo bash -c "7z x -bd -so $imagefile | pv --size $(7z l "$imagefile" | tail -1 | awk '{print $3}') --sync --output $device"
+		;;
+	iso)
+		sudo pv --sync --output "$device" "$imagefile"
+		;;
+	*)
+		echo "Unknown file extension: $ext"
+		exit 1
+		;;
+	esac
+}
+
 device=
 imagefile=
 
-usage() { printf "Use like:\n\t %s    [device]    [imagefile]\n\t %s -d [device] -i [imagefile]\n" "$0" "$0" 1>&2; exit 1; }
 while getopts "d:i:h" o; do
 	case "${o}" in
-		d)   device=${OPTARG}    ;;
-		i)   imagefile=${OPTARG} ;;
-		h|*) usage               ;;
+	d) device=${OPTARG} ;;
+	i) imagefile=${OPTARG} ;;
+	h | *) usage ;;
 	esac
 done
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 if [[ -z "$device" ]]; then
 	device=$1
@@ -27,46 +96,7 @@ fi
 
 if [[ -z "$device" || -z "$imagefile" ]]; then
 	usage
-elif [[ ! -f "$imagefile" ]]; then
-	echo "Image file '$imagefile' does not exist"
-	usage
 fi
 
-device_info=$(udevadm info --query=property --path="/sys/block/${device##*/}")
-device_bus=$(<<<"$device_info" perl -ne '/^ID_BUS=(.*)/ && print $1')
-device_size_suffixed=$(lsblk -o SIZE "$device" | head -2 | tail -1)
-device_size=$(<<<"$device_size_suffixed" perl -ne '/\s*([\d\.]+)G/ && print $1')
-
-set -x
-if [[ "$device_bus" != "usb" ]]; then
-	echo "Device $device is not a usb device?"
-	exit 2
-elif [[ "$(bc <<<"${device_size:-0} < 8")" -eq 1 ]]; then
-	echo "Device $device seems to be too small? $device_size_suffixed"
-	exit 1
-elif [[ "$(bc <<<"${device_size} > 512")" -eq 1 ]]; then
-	read -rp "Device is size $device_size_suffixed, seems a bit large, are you sure? [y/N] " res
-	case "$res" in
-		[yY]|[yY][eE][sS]) ;;
-		*)
-			echo 'Exiting'
-			exit 1
-	esac
-elif mount | grep -qF "$device"; then
-	echo "Device $device is mounted"
-	exit 1
-fi
-
-ext=${imagefile##*.}
-case "$ext" in
-	zip|7zip)
-		sudo bash -c "7z x -bd -so $imagefile | pv --size $(7z l "$imagefile" | tail -1 | awk '{print $3}') --sync --output $device"
-		;;
-	iso)
-		sudo pv --sync --output "$device" "$imagefile"
-		;;
-	*)
-		echo "Unknown file extension: $ext"
-		exit 1
-		;;
-esac
+check_device "$device" "$imagefile"
+flash_image "$device" "$imagefile"
